import { NextRequest, NextResponse } from 'next/server';
import { useOrchestratorStore } from '@/lib/orchestrator';
import { evaluateDecisionExecutionPolicy } from '@/lib/orchestrator/action-policy';
import { authorizeOrchestratorRequest } from '@/lib/orchestrator/rbac';
import { evaluateOrchestratorGuardrails, resolveActionTypeFromDecisionType } from '@/lib/orchestrator/policy-guardrails';
import type { Decision, DecisionPriority, DecisionType } from '@/types/orchestrator';

/**
 * GET /api/decisions
 * Get pending AI recommendations
 */
export async function GET() {
    try {
        // Read access is currently open for dashboard visibility.
        const orchestrator = useOrchestratorStore.getState();
        const pending = orchestrator.activeDecisions
            .filter(d => d.status === 'pending')
            .map((decision) => ({
                ...decision,
                executionPolicy: decision.executionPolicy || evaluateDecisionExecutionPolicy(decision, orchestrator.automationLevel),
            }));
        return NextResponse.json({ decisions: pending });
    } catch (error) {
        return NextResponse.json(
            { error: 'Failed to fetch decisions', details: (error as Error).message },
            { status: 500 }
        );
    }
}

/**
 * POST /api/decisions
 * Create a preview decision in pending status for orchestration testing.
 */
export async function POST(request: NextRequest) {
    try {
        const authz = authorizeOrchestratorRequest(request, 'decisions.create', {
            action: 'create decision preview',
            entityType: 'decision',
        });
        if (!authz.ok) {
            return authz.response;
        }

        const body = await request.json().catch(() => ({}));
        const orchestrator = useOrchestratorStore.getState();
        const previewApprove = Boolean(body?.previewApprove);
        const approvedBy = typeof body?.approvedBy === 'string' ? body.approvedBy : authz.actor.id;

        const type = (body?.type || 'spray') as DecisionType;
        const priority = (body?.priority || 'high') as DecisionPriority;
        const confidence = Number.isFinite(body?.confidence) ? Number(body.confidence) : 82;
        const riskToYieldScore = Number.isFinite(body?.riskToYieldScore) ? Number(body.riskToYieldScore) : (priority === 'critical' ? 92 : 68);
        const urgencyScore = Number.isFinite(body?.urgencyScore) ? Number(body.urgencyScore) : (priority === 'critical' ? 94 : 60);
        const economicsScore = Number.isFinite(body?.economicsScore) ? Number(body.economicsScore) : 70;
        const compositeScore = Number(((riskToYieldScore * 0.45) + (economicsScore * 0.4) + (urgencyScore * 0.15)).toFixed(2));

        const now = new Date();
        const expiresAt = new Date(now.getTime() + 6 * 60 * 60 * 1000);
        const recommendation = {
            id: body?.recommendationId || `rec-${Date.now()}`,
            action: body?.action || 'Apply preventive intervention',
            actionType: type,
            parameters: body?.parameters || {},
            confidence,
            rationale: body?.rationale || [{ title: 'Preview rule', detail: 'Generated for API validation.', source: 'rule' as const }],
            whyNow: body?.whyNow || 'Decision window is active.',
            deadline: expiresAt,
            expectedImpact: body?.expectedImpact || {
                yieldDeltaPct: 4.5,
                revenueDelta: 950,
                costDelta: -260,
                riskReductionPct: 18,
            },
            priorityScoring: body?.priorityScoring || {
                riskToYieldScore,
                economicsScore,
                urgencyScore,
                compositeScore,
                reasons: ['Preview scoring for orchestration validation'],
            },
            expectedCost: Number.isFinite(body?.expectedCost) ? Number(body.expectedCost) : 260,
            expectedRevenue: Number.isFinite(body?.expectedRevenue) ? Number(body.expectedRevenue) : 1180,
            expectedROI: Number.isFinite(body?.expectedROI) ? Number(body.expectedROI) : 354,
            timeWindow: body?.timeWindow || { start: now, end: expiresAt },
            explanation: body?.explanation || 'Preview decision explanation.',
            riskFactors: body?.riskFactors || (priority === 'critical' ? ['Severe agronomic risk', 'Narrow weather window', 'Operational constraints'] : ['Moderate operational risk']),
            prerequisites: body?.prerequisites || ['Operator available'],
        };

        const previewDecision: Omit<Decision, 'id' | 'createdAt'> = {
            type,
            status: 'pending',
            priority,
            fieldId: body?.fieldId || 'field-preview',
            cropId: body?.cropId,
            title: body?.title || `Preview ${type} decision`,
            description: body?.description || 'Generated by API preview route for approval workflow testing.',
            recommendation,
            alternatives: [],
            context: {} as any,
            expiresAt,
            autoExecuted: false,
            conflictAnalysis: {
                hasConflicts: false,
                conflictingDecisionIds: [],
                reasons: [],
                severity: 'low',
                recommendedResolution: 'No conflicts detected.',
            },
            executionPolicy: evaluateDecisionExecutionPolicy({ priority, recommendation } as any, orchestrator.automationLevel),
        };

        const created = orchestrator.addDecision(previewDecision);
        if (!previewApprove) {
            return NextResponse.json({ success: true, decision: created });
        }

        const guardrail = evaluateOrchestratorGuardrails({
            source: 'decision_approval',
            actionType: resolveActionTypeFromDecisionType(created.recommendation.actionType),
            controlMode: created.executionPolicy?.controlMode,
            priority: created.priority,
            parameters: created.recommendation.parameters,
        });
        if (guardrail.decision === 'block') {
            return NextResponse.json({
                success: false,
                error: 'Preview approval blocked by policy guardrails.',
                guardrail,
                decision: created,
            }, { status: 409 });
        }

        const approval = orchestrator.approveDecision(created.id, approvedBy);
        const updated = useOrchestratorStore.getState().activeDecisions.find((d) => d.id === created.id);
        return NextResponse.json({
            success: approval.success,
            approval,
            decision: updated || created,
            guardrail,
        }, { status: approval.success ? 200 : 409 });
    } catch (error) {
        return NextResponse.json(
            { error: 'Failed to create preview decision', details: (error as Error).message },
            { status: 400 }
        );
    }
}
